// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Company struct {
	ID          int64
	CompanyType string
	CompanyName string
	CreatedAt   time.Time
}

type Entry struct {
	ID        int64
	EntityID  sql.NullInt64
	Product   sql.NullInt64
	Amount    int32
	CreatedAt time.Time
}

type Order struct {
	ID            int64
	FromCompanyID int64
	ToCompanyID   int64
	Product       int64
	Amount        int64
	CreatedAt     time.Time
}

type Product struct {
	ID          int64
	ProductName string
	Origin      string
	CreatedAt   time.Time
}

type User struct {
	ID          int64
	FirstName   string
	LastName    string
	Email       string
	Password    string
	Company     int64
	AccessLevel int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
