// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Company struct {
	ID          int64
	CompanyType string
	CompanyName string
	CreatedAt   time.Time
}

type Entry struct {
	ID        int64
	CompanyID int64
	ProductID int64
	Amount    int32
	CreatedAt time.Time
}

type Order struct {
	ID            int64
	FromCompanyID int64
	ToCompanyID   int64
	ProductID     int64
	Amount        int32
	CreatedAt     time.Time
}

type Product struct {
	ID          int64
	ProductName string
	Description string
	CreatedAt   time.Time
}

type User struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
	Password  string
	CompanyID int64
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
